services:
  db:
    image: postgres:16
    container_name: tours_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: tours_db
      POSTGRES_USER: tours_user
      POSTGRES_PASSWORD: tours_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
