from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tours", "0002_local_image_paths"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS tours_tourimage (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                image_url varchar(255) NOT NULL,
                caption varchar(160) NOT NULL,
                tour_id bigint NOT NULL REFERENCES tours_tour(id) DEFERRABLE INITIALLY DEFERRED
            );
            CREATE INDEX IF NOT EXISTS tours_tourimage_tour_id_idx ON tours_tourimage (tour_id);
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
